### PR TITLE
Describe how shs connections should be done

### PR DESCRIPTION
**Pull request by staltz**
Extracted from https://github.com/ssb-ngi-pointer/ssb-secure-partial-replication-impl-spec/issues/1#issuecomment-881286640

Pending review

### CODE REVIEW

**Review by arj03 — APPROVED** [review]
Great summary. I'm happy that this leads to less changes overall. Very interested in what cryptix has to say. If there is anything that sticks out please sound the alarm :)

**Comment by cryptix** [comment]
I wouldn't say this is _less changes overall_. Compared to what? it just moves the changes elsewhere and while doing that, adds another stage to the handshake but on the muxrpc layer. From a purity perspective I'm strongly against this and would like to make explicitly clear that _that's in an repo where PRs might be annoying_ feels like a smokescreen and/or a very serious problem in itself.

Also, don't all the existing secret-stack plugins conflate _identity_ and _use-case_ (as they are called here) because they always were the same? I can't talk thoroughly about the JS stack but I guess a lot of the secret-stack `init()` has to be re-considered and changed, too?

> trial-and-error calling some muxrpc APIs.

This is too hand-wavy at the very least. We need to be really careful with this one and probably need some signing involved, similar to what `room.registerAlias` is doing to ensure a remote can't trick another peer into an unintended _use-case_.

To keep with the chess example, let's consider I have these three feeds (correct me if this assumption is wrong):

1) I have a metafeed (`@cryptix-mf`)
2) I have an old _classic_ feed which I hoisted onto the above (`@cryptix-p13za`)
3) I have a new chess subfeed (`@cryptix-$chess`)
4) My chess mate aleph has a similar setup (so `@aleph-mf`, `@aleph-classic` and `aleph-$chess`)

Problem one: We both are still using some other clients (like patchwork) and want to play chess now and per this proposal use `@cryptix-p13za` and `@aleph-classic` respectivl to connect to some room... How will I know which of the `aleph-classics`s in the room is the chess one if they all use the _classic_ keypair (which is all the room can see, unless it also adopts this stage2 muxrpc call)?

Problem two: Assuming there is just chess aleph and cryptix in a room without any ambiguities. Handshake completes and the `rpc.id`s are `@aleph-classic` and `@cryptix-p13za` respectively. Each side calls `async stage2.usecase $nonce` (the $nonce to protect against replays of the response on other sessions). What keypair is used to sign the response? It could be either the metafeed one or _classic_. The former means the application needs to hold all three secrets while with the latter, we don't even have a real relation between the connection and the application secrets so we should really be using the metafeed.

Lastly I want to raise the issue of upgradability: How will ssb ever transition out of this if we start doing this? Requiring this `stage2` call indefinitely feels dangerous and gnarly to deal with unless specified. OTOH It _could_ be said that shs1 already mixes the layers here because the connection and the feed is the same. I guess we are tip-toeing around this crux, really.

In addition, I want to raise the issue of key-rotation. If the _classic_ secret remains the de-facto identity what is the process for tombston-ing it?

**Comment by staltz** [comment]
Thanks for taking a look and putting words to the feelings.

> I wouldn't say this is _less changes overall_. Compared to what? it just moves the changes elsewhere

It moves the changes to new code to-be-written. I think that's better than doing breaking changes in existing code.

> adds another stage to the handshake but on the muxrpc layer

I don't see it as a handshake in any sense. A peer attempts to call a muxrpc API and that API might not be available, leading to the conclusion that the use case is not supported. That's already the case with blobs, rooms, and other publicly-facing muxrpc: if `remotePeer.blobs.has` does not exist, we can deduce that the remote peer does not support blobs as a use case. If `remotePeer.createHistoryStream` does not exist, we can deduct that the remote peer is probably a room.

> would like to make explicitly clear that _that's in an repo where PRs might be annoying_ feels like a smokescreen and/or a very serious problem in itself.

I read this a couple of times and couldn't understand. Making PRs to this spec repo is annoying? Why?

> This is too hand-wavy at the very least. We need to be really careful with this one and probably need some signing involved, similar to what room.registerAlias is doing to ensure a remote can't trick another peer into an unintended use-case.

It was vague on purpose because it's going to be different depending on the use case. Some (many!) use cases won't even need dedicated muxrpc APIs, they will only need to do replication. Chess, in fact, only needs replication.

> Also, don't all the existing secret-stack plugins conflate _identity_ and _use-case_ (as they are called here) because they always were the same? I can't talk thoroughly about the JS stack but I guess a lot of the secret-stack `init()` has to be re-considered and changed, too?

The JS stack typically has supported `N` use cases for `1` identity. E.g. among those N, there's social posts/votes, gatherings, chess, git-ssb, scat, etc. So `N:1` cannot be conflation, because it would have to be `N:N`, where each use case gets its own identity. In fact, if you use [ssb-identities](https://github.com/ssbc/ssb-identities), then you have `N` use cases (same as before) but now for `M` identities. So `N:M`, where there is one main "network identity" masking the multiple feeds you may be managing (same as my proposal). So, no, secret-stack plugins do not conflate `1:1` identity with use case.

> chess example
> 
> ...
> 
> Problem one: We both are still using some other clients (like patchwork) and want to play chess now and per this proposal use `@cryptix-p13za` and `@aleph-classic` respectivl to connect to some room... How will I know which of the `aleph-classics`s in the room is the chess one if they all use the _classic_ keypair (which is all the room can see, unless it also adopts this stage2 muxrpc call)?

I don't understand the question, there is only **one** `@aleph-classic`.

> Problem two: Assuming there is just chess aleph and cryptix in a room without any ambiguities. Handshake completes and the `rpc.id`s are `@aleph-classic` and `@cryptix-p13za` respectively. Each side calls `async stage2.usecase $nonce` (the $nonce to protect against replays of the response on other sessions). What keypair is used to sign the response? It could be either the metafeed one or _classic_. The former means the application needs to hold all three secrets while with the latter, we don't even have a real relation between the connection and the application secrets so we should really be using the metafeed.

The first two sentences are not in accordance with the proposal I'm making. `rpc.id` would **have** to be `@aleph-$chess` because the first sentence said that _chess aleph_ is in the room. But I'll comment on the second part of your quoted paragraph. In this Readme PR I wrote that

"_the chess app can prompt you to insert your 24 words of your main (classic) feed (in order to use that for shs), but you may choose to skip that and use a completely separate newly-created identity (for shs), just for chess._"

The *network public feed* (a terminology you [introduced here](https://github.com/ssb-ngi-pointer/ssb-secure-partial-replication-impl-spec/issues/1#issuecomment-866106407), which I dig) can be the main (i.e. classic) feed or can be the chess feed. The muxrpc idea I'm suggesting could be based on replicating the meta feed. Both `@aleph-$chess` and `@aleph-classic` are by design aware of `@aleph-mf`, so whether the network feed is `@aleph-$chess` or `@aleph-classic` doesn't matter, both can present to you (`@cryptix-p13za`) the meta feed messages for `@aleph-mf`. To figure out which use cases are supported, `@cryptix-p13za` can look into the messages under `@aleph-mf` and discover that `@aleph-$chess` exists and is meant for the `feedpurpose: "chess"`, and thus `@cryptix-p13za` can replicate `@aleph-$chess`, it doesn't matter what the *network ID* of Aleph actually is.

> Lastly I want to raise the issue of upgradability: How will ssb ever transition out of this if we start doing this? Requiring this `stage2` call indefinitely feels dangerous and gnarly to deal with unless specified. OTOH It _could_ be said that shs1 already mixes the layers here because the connection and the feed is the same. I guess we are tip-toeing around this crux, really.
> 
> In addition, I want to raise the issue of key-rotation. If the _classic_ secret remains the de-facto identity what is the process for tombston-ing it?

I didn't propose to cement the classic ID as the only network ID. In this Readme PR I mentioned:

"_In practical terms in the SSB stack, use the main feed ID (**or whatever ID most of your peers recognize you by**)_"

The "whatever" there was hinting towards meta feeds. Peers could announce that their new network ID is now the meta feed, and then they would need to update their memberships in rooms and overall just let their friends know to follow this new ID. In this process, using the technique [you mentioned](https://github.com/ssb-ngi-pointer/ssb-secure-partial-replication-impl-spec/issues/1#issuecomment-866106407):

> special message on a metafeed that announces the network public key

**Comment by arj03** [comment]
The more I think about it, the more I like adding a network identity meta feed to define network identities. This is one step closer to properly splitting identity and feeds.

These keys could overlap with the feed keys but don't have to. From a security point of view this would allow a network process to only know a key that can be used for shs connections. So a compromise would not be the end of the world. Another use case this allows is encrypted network identities. Meaning only certain people would know that a certain network identity is you, for everyone else you would just look like a rando.

This would also us to split the identities (for things like [ssb-conn-firewall](https://github.com/staltz/ssb-conn-firewall) and ssb-friends) from what feeds you want to replicate (this should be application specific). Both needs to take meta feeds into account.

**Comment by staltz** [comment]
Really interesting! I like it

**Comment by arj03** [comment]
One thing to add to this network identity is that if they have a feed, they should announce the metafeed similar to the main feed. I don't think these cloaked identities should have a feed, the idea is that you would have their meta feeds and thus network identity feed by replicating another feed already.

**Comment by arj03** [comment]
Summary from the meeting with @cryptix is that he is on board with the network identity idea (had some great comments) so I'll write a counter PR with that sketched out. What do you think about that @staltz?

**Comment by staltz** [comment]
> What do you think about that @staltz

Curious :)

**Comment by arj03** [comment]
@staltz https://github.com/ssb-ngi-pointer/ssb-network-identity-spec

**Comment by staltz** [comment]
@arj03 The new spec looks good (minus details/typos), and it helps clarify this PR in more details, but what about room membership? The room won't know about chess (network) IDs, and won't replicate the meta feed (nor will it replicate the `networkidentities` bendy butt feed), so the solutions described in this PR are still necessary.

**Comment by arj03** [comment]
I'm not sure if we need to specify that case. Reusing main identity for chess application is only needed if one does not register the chess identity in the room. Adding the chess identity has the upside that you don't need to care about the case where multiple applications with the same main identity are connected. As discussed in #10, adding an application is anyway a manual action and we could look into making it easier to add members to the room using an api in the community model. This leaves the restricted mode as the real bummer. On the other hand this might also encourage more room servers to be spawned. Like happy did set up a special room server for his browser chess application.

**Comment by staltz** [comment]
> Reusing main identity for chess application is only needed if one does not register the chess identity in the room.

I think it's more likely that people will not manually register app identities in rooms they are part of, for three reasons: (1) manual work is always likely to be avoided as much as possible, (2) people seem to prefer to want to have one simple identity which is used and shared everywhere (see e.g. people copy-pasting their `~/.ssb/secret` across several devices despite our repeated warnings against that), (3) people may be member of N (preferably `N > 1`!) rooms, so for each new app they use, they might need to manually register the new app feed ID in N rooms.

The suggestion is definitely simple for us to implement, but from a UX perspective I'm afraid we can't rely on people manually setting up things in all use cases. If we want to see an ecosystem where hundreds of apps flourish with their own app feed ID, then I think we need to consider how to make it easy and automatic for all these things to integrate seamlessly.

**Comment by arj03** [comment]
I think it might be good to continue this conversation when we meet IRL in Svendborg.

**Pull request closed without merging**
